experiment_name: "baseline_fl_demo_short"
num_clients: 10
num_attackers: 2
rounds: 10
dataset: "CIFAR10"
model: "SimpleCNN"
attacks:
  - type: "label_flipping"
    target_label: 7
defenses:
  aggregation: "krum"
  differential_privacy: true
  dp_std: 0.1
  dp_clip: 1.0
  trust_system: true
logging:
  output_dir: "logs/"
